# Generated by Django 4.2 on 2023-04-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='status',
            new_name='type',
        ),
    ]
